### PR TITLE
Improve performance for constrained objects

### PR DESCRIPTION
**Pull request by Zac-HD**
Closes #12.

@lykahb - I'd love it if you could test this branch.  If you have a schema that has poor performance (e.g. triggers any health check), and can share it, I'd love to add that to the test suite.  If I don't hear back, I'll merge it and release 0.8.2 over the weekend.

### CODE REVIEW

**Comment by lykahb** [comment]
Thank you, this fix works. Here is a simplified schema that still gives error

```
E   hypothesis.errors.FailedHealthCheck: It looks like your strategy is filtering out a lot of data. Health check found 50 filtered examples but only 9 good ones. This will make your tests much slower, and also will probably distort the data generation quite a lot. You should adapt your strategy to filter less. This can also be caused by a low max_leaves parameter in recursive() calls
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.filter_too_much to the suppress_health_check settings for this test.
```

``` Python
{'type': 'object',
 'properties': {
     'ids': {
         'type': 'array',
         'minItems': 1,
         'uniqueItems': True,
         'items': {
             'type': 'string',
             'pattern': '^\\d+$'}}},
 'additionalProperties': False,
 'required': ['ids']}
```

**Comment by lykahb** [comment]
The tests started failing again after a schema change and clearing .hypothesis. The library tries to draw keys even if all available keys are already in `out`.

```python
key = draw(all_names_strategy.filter(lambda s: s not in out))
```

```python
{'$schema': 'draft4', 'type': 'object',
                      'properties': {'title': {'type': 'string', 'enum': ['theonlyvalue']},
                                     'id': {'type': 'string', 'pattern': '^\\d+$'},
                                     'value': {
                                         'type': 'object',
                                         'properties': {
                                             'flag': {
                                                 'type': 'boolean'},
                                             'string': {
                                                 'anyOf': [
                                                     {
                                                         'type': 'string'},
                                                     {
                                                         'type': 'null'}]},
                                             'ids': {
                                                 'type': 'array',
                                                 'minItems': 1,
                                                 'uniqueItems': True,
                                                 'items': {
                                                     'type': 'string',
                                                     'pattern': '^\\d+$'}}},
                                         'additionalProperties': False,
                                         'required': [
                                             'ids',
                                             'flag',
                                             'string']}},
                      'additionalProperties': False, 'required': ['title', 'value', 'id']}
```

**Comment by Zac-HD** [comment]
@lykahb - done!  Let me know if you still have any issues 😄 

Turns out that the whole issue of overlapping patternProperties was a complete red herring, though I've got a good lead on that too now... we'll see how it turns out.

**Comment by Zac-HD** [comment]
I'm delighted to hear it, and glad you've found the library useful 😁

**Pull request merged**
