### PR TITLE
Handle unsatisfiable schema case when numeric range does not contain any numbers divisible by `multipleOf`

### PR DESCRIPTION
**Pull request by Stranger6667**
Similar logic should apply to `integer` type as far as I can see. What do you think? will this approach work? If yes, then I can extend it to integers as well :)

Also, I am not sure about correct wording in the variable names & docstrings

Regards

### CODE REVIEW

**Comment by Zac-HD** [comment]
Nice!  I'm definitely keen to get this working - hence the `xfail` test case :wink: 

Integers are already handled, since I adjust the bounds up or down to the nearest allowed integer.  I think this approach is promising, but it's trickier than it looks:

The `multipleOf` need not be a whole number!  That means adding or subtracting `1` changes the semantics of the operation.  On the other hand, you can probably copy the logic from `integers` so long as you cast everything to a `Fraction` and then convert to a common denominator first!

**Comment by Stranger6667** [comment]
> Integers are already handled, since I adjust the bounds up or down to the nearest allowed integer

Great :)

> That means adding or subtracting 1 changes the semantics of the operation

It seems like I am missing something. In `has_divisibles` it counts the number of numbers that are divisible by `divisor` in that range, however, I don't see how float `multipleOf` will change the logic :( Currently, I see it like this - subtracting excludes boundary values if needed. E.g. if `end` is divisible by `divisor` and `exmax` is `True` then it is excluded from the total number of divisible numbers. By default `start` should be added as extra if it is divisible by `divisor` (e.g. there are 2 numbers divisible by 3 in [3; 6] range, but the first line in the function will be evaluated to `1`) and then it is not added to the total number if it is divisible by `divisor` and `exmin` is `True`. 
What do you think? Could you please, elaborate?

**Comment by Zac-HD** [comment]
(failure is an unrelated coverage blip, so merging anyway)

**Comment by Stranger6667** [comment]
Great, thanks! :)

**Pull request merged**
